CREATE DATABASE PIM_VIII;

use PIM_VIII;

CREATE TABLE ENDERECO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOGRADOURO VARCHAR(256),
	NUMERO INT,
	CEP INT,
	BAIRRO VARCHAR(50),
	CIDADE VARCHAR(30),
	ESTADO VARCHAR(20)
);

CREATE TABLE PESSOA (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(256),
	CPF BIGINT,
	ENDERECO INT FOREIGN KEY REFERENCES ENDERECO(ID)
);

CREATE TABLE TELEFONE_TIPO (
	ID INT PRIMARY KEY,
	TIPO VARCHAR(10)
);

INSERT INTO TELEFONE_TIPO VALUES (1, 'TELEFONE');
INSERT INTO TELEFONE_TIPO VALUES (2, 'CELULAR');
INSERT INTO TELEFONE_TIPO VALUES (3, 'COMERCIAL');
INSERT INTO TELEFONE_TIPO VALUES (4, 'FAX');

CREATE TABLE TELEFONE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NUMERO INT,
	DDD INT,
	TIPO INT FOREIGN KEY REFERENCES TELEFONE_TIPO(ID)
);

CREATE TABLE PESSOA_TELEFONE (
	ID_PESSOA INT FOREIGN KEY REFERENCES PESSOA(ID),
	ID_TELEFONE INT FOREIGN KEY REFERENCES TELEFONE(ID),
	PRIMARY KEY (ID_PESSOA, ID_TELEFONE)
);